/*
* @Name         ConstantClass 
* @Author       Soham Datta
* @Date         26/01/2023
* @Description  Constant Class
*/
public with sharing class ConstantClass {

    public static final String HISTORY = 'history';
    public static final String TAG = 'tag';
    public static final String SHARE = 'share';
    public static final String FEED = 'feed';
    public static final String GROUPOBJ = 'group';
    public static final String PUBLICOBJ = 'public';
    public static final String OBJ_NAME_MISSING = 'ObjectName is missing. Please select an object';
    public static final String DEFAULT_LIMIT = '10';
    public static final String NAME_FIELD = 'Name';
    public static final String CREATEDBYID_FIELD = 'CreatedById';
    public static final String CREATEDDATE_FIELD = 'CreatedDate';
    public static final String SELECT_QUERY = 'Select ';
    public static final String FROM_QUERY = ' From ';
    public static final String ORDERBY_QUERY = ' Order By CreatedDate Desc Limit ';

}